### ISSUE TITLE
[PA Review] Authentication

### ISSUE THREAD

**Issue by matthaaa** [matthaaa/instagraph#10]
- [x] Backend Authentication
- [x] Frontend Authentication
- [x] Presentational Components - LogIn and SignUp views
- [x] Styling for components
- [x] Smooth, bug-free navigation
- [x] Adequate/appropriate seeds

**Comment by matthaaa** [comment]
https://instagraph-aa.herokuapp.com/#/

**Comment by dobrynin** [comment]
I get an error when trying to sign up.

**Comment by matthaaa** [comment]
Looking into it!

**Comment by dobrynin** [comment]
good to go!
